name: CD - Deploy to AWS

on:
  push:
    branches: [ main ]
    # Only run this workflow if the CI pipeline was successful
    # This assumes your CI workflow is named 'CI & Security Pipeline'
    paths-ignore:
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This job will only run if the build jobs in the CI pipeline succeed
    needs: [build-backend, build-frontend] # From the ci-security-pipeline.yml file

    permissions:
      id-token: write # Required for authenticating to AWS
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsDeployRole # You will create this role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve